kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgB7WMGP0poVKVBVSgsZUu/sTpL5PtxgRWz0S6b7Qisb6VYj9xwJeONYneaZO/R9qc1cIJWmNiEl2FDTLgspQxrQMg6xS/JEfvwOYoZ1lb8FQrFYsBTVK0LZTR37m1V2cVZETh45CqZ9UI3JFnYVRiVZ4/dIWiUg6hCK1rlqPi0Q/03SO3Wotl3cuNbBwYkyjrWt5DZTtvHHAHETUdqbAUUL5mEuPxoe3kDxz7k9wgxnxl6FQyjW/GFfRueiv7sf2oX+ztcFFcJj3VbO1einuHs/sjlEl2/FqCpu7JfZVhwhbB0e7Rv8Oc8WAm90zSFmuDlSRLT7dchuYHBKrJTzJOrDGagtHd+4GvgiMujRJqp2V3LBe+YzmIE1/WVjImpUArZrlBfOvj75wh/KorAPtRry/Db+84j4h0j/d2QNyhtCno7E6HtVke7MRRkMvCCQzMN8vJO491DkO+BTLQgOqXw6fBj3GWFlrziPIzlPKumIzm1Ydv7B3GUXC6k8tK7AQbLmGBc0OWKJERHy5OLr+kBGUkcbdrbGjSu3hfsxK2hC+Bsj4BmUfqfPtZlYq7IeQdVueH54l0VidC7yVzdQ5GNgxp6tJ0+rqPyZP9UftbIAqlG9lqmFP0xl66Un+JNor0iWNrq8S0t76diZn8Dempek/9sVZ/Se3lviqC+LC9b7fkbWFwi4j4BOgKO1yhvR9u78Iio2Ija+wLiR
    admin-user: AgBtS4W+lQDSBEj95UtaqFDGQX5M6a1zmRwD2LvI76EK9V9knQ3qcGpq8ddaDjjL4bbyvdxmDp1bSWOStlVWgzALDQgF2bJrpdiq3jSEd/KbdmfMZ892vYdXsmW6pOQEjjicYXFKTQpG12TJangnfY8BwN9yUEW+VpX21zAkynM9ZSKj2d1GKxiId9DSlJefeodMguNHdXnESUDs2yZ8AsKYqtb8irrU39WQIVoBv3pbm/itMvkcDejRDSvTrYwwBjlCP+R1ZUg1Ll0ijvJN5CTQVbj0nVRibN/sLSfialMT38geyLTBeU1+D5pI9NBN8XnbBEqmUZBofoUwWGaf4eMw8I9AAR9Ro3jNU4qnZ+v3QV8ngPCNpAa9hzXBMRJFjZKlg17ruk8GT/wUAcGZktwjU7f4yQ/68W1QuBLWSswv+esOzvx4mWemr39q+F6bqSKzWA23+j0EnTsP97d673VyPVRqyRXEFOJXIVxxQpgV3gVXb7Q1QWv41xied67q30r7B4TN0EYmpP+GhtXPhvHhoZhFEEUTQ88r3ZKXOqZSMuACvTWNSCyv+1zdrPwiYopncLtqGYFNy9lIiO/Yh5/4yvGsN1k4aE7QJN+lIa3AiaI5Krq048uzJrU1gMDifo5xF6rauR9CMDKnUoGv7zGmFkmutj2YFz5Gd8SiWTMIII0SJsud9XF2D5o1gkK22umSsPqB1w==
