apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kiali-abs-cloud-nl
  namespace: istio-system
spec:
  secretName: kiali-abs-cloud-nl
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kiali.abs-cloud.nl
  dnsNames:
    - kiali.abs-cloud.nl
