apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- authorization-policy.yaml
- grafana-cert.yaml
- grafana-virtual-service.yaml
- kiali-cert.yaml
- nvidia-dcgm-service-monitor.yaml
- nvidia-dcgm-exporter-dashboard.yaml
- pod-metrics-dashboard.yaml
- namespace.yaml
