apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/kubeflow/components/crud-web-apps/volumes/manifests/overlays/istio?ref=90e987bf87d3e7c900926310b00bfa16b59e41eb # tag=v1.10.0

images:
- name: public.ecr.aws/j1r0q0g6/notebooks/volumes-web-app
  newName: public.ecr.aws/j1r0q0g6/notebooks/volumes-web-app
  newTag: v1.3.0-rc.1
