apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- keycloak-secret.yaml
- kubeflow-realm-secret.yaml
- oauth2-proxy-secret.yaml
- oauth2-signout-virtual-service.yaml
- virtual-service.yaml
