apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/kubeflow/components/admission-webhook/manifests/overlays/cert-manager?ref=315ee7e305e8b7485c975283fb7e5751d21f267d # tag=v1.9.2

images:
- name: public.ecr.aws/j1r0q0g6/notebooks/admission-webhook
  newName: public.ecr.aws/j1r0q0g6/notebooks/admission-webhook
  newTag: v1.3.0-rc.1
