apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-abs-cloud-nl
  namespace: istio-system
spec:
  secretName: auth-abs-cloud-nl
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: auth.abs-cloud.nl
  dnsNames:
    - auth.abs-cloud.nl
