apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: allow-monitoring
 namespace: kubeflow-user
spec:
 action: ALLOW
 rules:
 - from:
   - source:
      namespaces:
      - monitoring
