apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: notebook-instances
  namespace: monitoring
  labels:
    app: notebook-instances
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      notebook-name: "gpu"
  podMetricsEndpoints:
  - path: /notebook/kubeflow-user/gpu/metrics
    # targetPort: "8888"
    interval: 5s
