apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/kubeflow/components/crud-web-apps/jupyter/manifests/overlays/istio?ref=90e987bf87d3e7c900926310b00bfa16b59e41eb # tag=v1.10.0

patchesStrategicMerge:
- spawner_ui_config.yaml
- logos-configmap.yaml

images:
- name: public.ecr.aws/j1r0q0g6/notebooks/jupyter-web-app
  newName: davidspek/jupyter-web-app
  newTag: 0.25.24
