kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: registry-storage
  namespace: gitlab
  creationTimestamp: null
spec:
  template:
    metadata:
      name: registry-storage
      namespace: gitlab
      creationTimestamp: null
    data: null
  encryptedData:
    config: AgABMYX/ed0RODDLuNBpc13qNXfTz+IHLH4SfhnfbSR+cmq/nxYc4D3E9tc79vedzmzNKrUiHUD/0WFh2g1Lryvnyfehpu/F6hV36tdw1RmTGDssGGbtD69+DNCj1IaLk5TjKRjzgOogOkK3VF5BkqBg3E+w+yDUdg3h7JZe5aq3ZOx0pQSpaWIr5A5sSPguCcVuV9eeGSp/dYGn7vpNNR77ls2S08vX734SC9d7tpZ/h2jQY+vUJWsreF3VQYtxU+/WIsEQRsHJaN4EkxHK5tTkkC4YbXJP0sPHimv3Fw9xX+Vp+IrafQs2pHgnnjlJ/JC8hMpINmuQGaZPaCtW+gUQ3A0vr9G+qm3MMww+Kll/GkhnHUOz3KJmd1qt0X6NarqOk4wLb0axjSVfB+JoZCkIWGnbfEOJ8M/JI9ds6awpJ9eCna/2sblxh0slTXOPtBGBTtwfHz/KCx/aH9QpeseBqQgOZxIscxYB0P2/ooz7IiSV9/QVTxKvIvD5SOW/n46R+8tHDLYzVttAVS/rlPDcoMfnQC0Wiz00Z7Jj4PImJDKxeLVyBz62T3cmYoyPWEJpcgItBrXcWJTL2WGO+dbRrhJ049S7bRFVl0MzVk5rYXcLQT70r14fo/ZWycbUDEaQfgE5BdC+Ecf69AaB8+Ia8GRF6XsmUj1XBn+7Vzi9dXGtcFlU8haY+Az7d961usnmFkd449siuT0FJ5bktnLoNyhBg47jKpODyBtC5B6O00L6iuTycT5G+GACscxfGHBn7DT0aWTI1xQlYHK4F6GDB6zFyWXvz1gj8ZIqvbx2d4B6V2voVFuAZQ5AqUgcaMhzulcoCsv2vnejgIC1/HAQdIcjCUqdMca2kFFkzoYoK8G3h2PYW2vdYRSXKw4A6Rz9Zk3SgaRHMq7n/KHpQZYaH0jbmeqLmJeV76iYOQA2a8gXmvUf0oGxxtcU/5FceJCfNk2mYT8GTlBfIVhfNJUtNJa3c9lsEhA+n8URn6FlwR7dzSThHZioYbXm9g3TcV1LUq10vDh//F+7F9zak19Fhp0hCI0enPlzr1JMkSZOeVreuReIXvDYSZxcRobJVcjRX4QnPoQtZqwXh/0kYh3BpOoZS80FAGDqmJPL/m+kRksMQD2mT+eRf1pok8ijzAaBjrreEokeePqfeFYsN3fCL4IlPA/GqWvU9ymbKT8U5ydRvbZ8ZPAHF7WmB+w8JwLkyfeD53sYItPIA8Qf099gWIaPw/E4kSOkTEwKqPeh7v2Qp+qFKMZKhwDNPDJrsgSXbEW4DRFENWZKpZNRyOmFAx6161sw6hU4PDXSgdD09i9ixhYB7VedO/mS0+ai7+iP2Isq8QwmVZAap4rf9omNVYUZQTTVEHQdWTDiGC6QC8Ad7t9HNsks4Qj076lMghlL2pN/cZqp7zZq7WAiguIzYbGGzV13sEkyQO+1z49L/gSVAgMzulw=
