issuer: https://auth.abs-cloud.nl
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  http: 0.0.0.0:5556
logger:
  level: "debug"
  format: text
oauth2:
  skipApprovalScreen: true
expiry:
  signingKeys: "4h"
  idTokens: "1h"
enablePasswordDB: true
staticPasswords:
- email:
  hash:
  # https://github.com/dexidp/dex/pull/1601/commits
  # FIXME: Use hashFromEnv instead
  username:
  userID: "15841185641784"
staticClients:
# https://github.com/dexidp/dex/pull/1664
- id:
  redirectURIs:
  - "https://kubeflow.abs-cloud.nl/oauth2/callback"
  name: 'Dex Login Application'
  secret:
connectors:
- type: gitlab
  # Required field for connector id.
  id: gitlab
  # Required field for connector name.
  name: GitLab
  config:
    # optional, default = https://gitlab.com
    baseURL: https://gitlab.abs-cloud.nl
    # Credentials can be string literals or pulled from the environment.
    clientID: ${GITLAB_CLIENT_ID}
    clientSecret: ${GITLAB_CLIENT_SECRET}
    redirectURI: https://auth.abs-cloud.nl/callback
    # Optional groups whitelist, communicated through the "groups" scope.
    # If `groups` is omitted, all of the user's GitLab groups are returned when the groups scope is present.
    # If `groups` is provided, this acts as a whitelist - only the user's GitLab groups that are in the configured `groups` below will go into the groups claim.  Conver>
    # groups:
    # - my-group
    # flag which will switch from using the internal GitLab id to the users handle (@mention) as the user id.
    # It is possible for a user to change their own user name but it is very rare for them to do so
    useLoginAsID: false
