apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy
  namespace: auth
data:
  client-id: oauth2-proxy
  client-secret: pUBnBOY80SnXgjibTYM9ZWNzY2xreNGQok
  cookie-secret: OQINaROshtE9TcZkNAm-5Zs2Pv3xaWytBmc5W7sPX7w=
