apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/kubeflow/kfserving/config/overlays/kubeflow?ref=7e4364246449715b902dc967167e38b38773c9cd # tag=v0.14.0

# patchesStrategicMerge:
# - kfserving-config-patch.yaml

images:
- name: gcr.io/kfserving/kfserving-controller
  newName: gcr.io/kfserving/kfserving-controller
  newTag: v0.6.0-rc0
  # digest: sha256:5ba6932090d1ace250309226c54d8c8bb1d754ca4c6650995205d17d6adb6e83
