apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
  namespace: argocd
spec:
  destination:
    namespace: auth
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: dex
    helm:
      parameters:
      - name: configSecret.create
        value: "false"
      - name: configSecret.name
        value: dex-config
    repoURL: https://charts.dexidp.io
    targetRevision: 0.3.3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
