apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/istio/istio'
    targetRevision: HEAD
    path: manifests/charts/istio-operator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
