apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 14.9.0
    chart: kube-prometheus-stack
    helm:
     parameters:
      - name : grafana.ingress.enabled
        value : "true"
      - name: grafana.ingress.hosts[0]
        value: grafana.abs-cloud.nl
      - name: grafana.ingress.tls[0].secretName
        value: grafana-abs-cloud-nl
      - name: grafana.ingress.tls[0].hosts[0]
        value: grafana.abs-cloud.nl
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
