apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-feature-discovery
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://nvidia.github.io/gpu-feature-discovery
    targetRevision: 0.4.1
    chart: gpu-feature-discovery
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
