apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-abs-cloud-nl
  namespace: argocd
spec:
  secretName: argocd-abs-cloud-nl
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: argocd.abs-cloud.nl
  dnsNames:
    - argocd.abs-cloud.nl
