apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- istio-spec.yaml
- namespace.yaml
- envoy-filter-kubeflow-userid.yaml
- kubeflow-certificate.yaml
- kubeflow-gateway.yaml
- deny-all-authorizationpolicy.yaml
- gateway-authorizationpolicy.yaml
- kubeflow-cluster-roles.yaml
- monitoring/
