apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: metricbeat-cluster
  namespace: logging
spec:
  type: metricbeat
  version: 7.13.1
  elasticsearchRef:
    name: elasticsearch-cluster
  kibanaRef:
    name: kibana
  config:
    metricbeat:
      autodiscover:
        providers:
        - hints:
            default_config: {}
            enabled: "true"
          host: ${NODE_NAME}
          type: kubernetes
      modules:
      - module: system
        period: 10s
        metricsets:
        - cpu             # CPU usage
        - load            # CPU load averages
        - memory          # Memory usage
        - network         # Network IO
        - process         # Per process metrics
        - process_summary # Process summary
        - uptime          # System Uptime
        - socket_summary  # Socket summary
        - core           # Per CPU core usage
        - diskio         # Disk IO
        #- raid           # Raid
        - socket         # Sockets and connection info (linux only)
        #- service        # systemd service information
        process:
          include_top_n:
            by_cpu: 20
            by_memory: 20
        processes:
        - .*
      - module: system
        period: 1m
        metricsets:
        - filesystem
        - fsstat
        processors:
        - drop_event:
            when:
              regexp:
                system:
                  filesystem:
                    mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib)($|/)
      # - module: kubernetes
      #   enabled: true
      #   period: 10s
      #   host: ${NODE_NAME}
      #   hosts: ["https://${NODE_NAME}:10250"]
      #   bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      #   ssl:
      #     verification_mode: none
      #   metricsets:
      #   - node
      #   - system
      #   - pod
      #   - container
      #   - volume
        add_metadata: true
      # - module: kubernetes
      #   enabled: true
      #   metricsets:
      #   - state_node
      #   - state_daemonset
      #   - state_deployment
      #   - state_replicaset
      #   - state_statefulset
      #   - state_pod
      #   - state_container
      #   - state_cronjob
      #   - state_resourcequota
      #   - state_service
      #   - state_persistentvolume
      #   - state_persistentvolumeclaim
      #   - state_storageclass
      #   # Uncomment this to get k8s events:
      #   #- event  period: 10s
      #   hosts: ["kube-state-metrics.kube-system:8080"]
      #   add_metadata: true
      # - module: kubernetes
      #   enabled: true
      #   metricsets:
      #     - apiserver
      #   hosts: ["https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}"]
      #   bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      #   ssl.certificate_authorities:
      #     - /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      #   period: 30s
      # - module: kubernetes
      #   enabled: true
      #   metricsets:
      #     - proxy
      #   hosts: ["localhost:10249"]
      #   period: 10s
      # - module: kubernetes
      #   enabled: true
      #   metricsets:
      #     - controllermanager
      #   hosts: ["http://localhost:10252"]
      #   period: 10s
      # - module: kubernetes
      #   enabled: true
      #   metricsets:
      #     - scheduler
      #   hosts: ["localhost:10251"]
      #   period: 10s
      # - module: ceph
      #   metricsets:
      #     - mgr_cluster_disk
      #     - mgr_osd_perf
      #     - mgr_pool_disk
      #     - mgr_osd_pool_stats
      #     - mgr_osd_tree
      #   period: 1m
      #   hosts: [ "http://rook-ceph-mgr.rook-ceph:9283" ]
      # - module: prometheus
      #   period: 10s
      #   hosts: ["http://rook-ceph-mgr.rook-ceph:9283"]
      #   metrics_path: /metrics
    processors:
    - add_cloud_metadata: {}
    - add_host_metadata: {}
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: metricbeat
        automountServiceAccountToken: true # some older Beat versions are depending on this settings presence in k8s context
        containers:
        - args:
          - -e
          - -c
          - /etc/beat.yml
          - -system.hostfs=/hostfs
          name: metricbeat
          volumeMounts:
          - mountPath: /hostfs/sys/fs/cgroup
            name: cgroup
          - mountPath: /var/run/docker.sock
            name: dockersock
          - mountPath: /hostfs/proc
            name: proc
          - mountPath: /hostfs/sys/block
            name: block
          - mountPath: /hostfs
            name: root
          - mountPath: /hostfs/run/systemd/private
            name: systemd
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true # Allows to provide richer host metadata
        securityContext:
          runAsUser: 0
        terminationGracePeriodSeconds: 30
        volumes:
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroup
        - hostPath:
            path: /var/run/docker.sock
          name: dockersock
        - hostPath:
            path: /proc
          name: proc
        - hostPath: 
            path: /sys/block
          name: block
        - hostPath:
            path: /
          name: root
        - hostPath:
            path: /run/systemd/private
          name: systemd
---
# permissions needed for metricbeat
# source: https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-kubernetes.html
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricbeat
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - namespaces
  - events
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "extensions"
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/stats
  verbs:
  - get
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metricbeat
  namespace: logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metricbeat
subjects:
- kind: ServiceAccount
  name: metricbeat
  namespace: logging
roleRef:
  kind: ClusterRole
  name: metricbeat
  apiGroup: rbac.authorization.k8s.io
---
