apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- serving-core-v0_22_0.yaml
- net-istio-v0_22_0.yaml
- eventing-core-v0_22_0.yaml # Eventing is optional
- monitoring/

images:
- name: gcr.io/knative-releases/knative.dev/serving/cmd/activator
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/activator
  digest: sha256:cc39d40985f7b37ba384a857d194a24ac5eae7e204aac4ed9bf4ebfd8d62e721
- name: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
  digest: sha256:59c2e7ad52cea17bedfc2aca9b9e33060bb34f04d35fd71fe61147bcbdb881e4
- name: gcr.io/knative-releases/knative.dev/serving/cmd/webhook
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/webhook
  digest: sha256:d42e2f83c9018779465860fdc67ce6ada3eac8ba8c47c5c2127c0bb45f9b328a
- name: gcr.io/knative-releases/knative.dev/serving/cmd/controller
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/controller
  digest: sha256:0e47362d044f8eac84595ed0a9fdf22e5dd5a07cc7a5df74e93eb5ad17ad4827
- name: gcr.io/knative-releases/knative.dev/net-istio/cmd/controller
  newName: gcr.io/knative-releases/knative.dev/net-istio/cmd/controller
  digest: sha256:781a242ee3f5fcf79264b98c65aff8185427404c51ab8ff723e2ebfaf085c593
- name: gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook
  newName: gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook
  digest: sha256:846e3e40ac21966cbaa4e2aeaa856f0faa8fb26cfaf8e23baada1bad4087be8e
# Eventing is optional
- name: gcr.io/knative-releases/knative.dev/eventing/cmd/controller
  newName: gcr.io/knative-releases/knative.dev/eventing/cmd/controller
  digest: sha256:806330a39dfac379cd39a771c2e42f3a9998d0f214fe38f28bcb101c554a5a7a
- name: gcr.io/knative-releases/knative.dev/eventing/cmd/webhook
  newName: gcr.io/knative-releases/knative.dev/eventing/cmd/webhook
  digest: sha256:be90d7813786da265dbda2408742b4783e4f69e73719cb3b6e2c103d631ed721
- name: gcr.io/knative-releases/knative.dev/eventing/cmd/mtping
  newName: gcr.io/knative-releases/knative.dev/eventing/cmd/mtping
  digest: sha256:1ccb821e1a4edf4cb6b35449e1ec9d03c9098d9a19361a06c0e8f6fc6dd2117a
