apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- certificate.yaml
- serving-core-v0_22_0.yaml
- net-istio-v0_22_0.yaml
- eventing-core-v0_22_0.yaml # Eventing is optional
- monitoring/

images:
- name: gcr.io/knative-releases/knative.dev/serving/cmd/activator
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/activator
  digest: sha256:e5ab46f3b73fa2e3898fe47f6a3a0c2bd765596f4fb36ceb4c28c35d0a74b2e5
- name: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/autoscaler
  digest: sha256:879da127b23db65d862cafa6b23fb987381d0e44150f0027d44e1f5aee83bde2
- name: gcr.io/knative-releases/knative.dev/serving/cmd/webhook
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/webhook
  digest: sha256:3846e9a416665c5b9ec2e4de246cfcb5c4ab0d01ba19348aa008caf30144b650
- name: gcr.io/knative-releases/knative.dev/serving/cmd/controller
  newName: gcr.io/knative-releases/knative.dev/serving/cmd/controller
  digest: sha256:ca5062ece0329d002a81940cf4268d7898866434d70049bb93f27d3a786d3292
- name: gcr.io/knative-releases/knative.dev/net-istio/cmd/controller
  newName: gcr.io/knative-releases/knative.dev/net-istio/cmd/controller
  digest: sha256:cf1530d3b625d247114f006e4902ba8c0f2a3196d1d7a6b7acbeb7d7db11d148
- name: gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook
  newName: gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook
  digest: sha256:ac5c0458f32e353a635919ccd89fe77a7bf650c5354dd76c71e9316eff5de65d
# Eventing is optional
- name: gcr.io/knative-releases/knative.dev/eventing/cmd/controller
  newName: gcr.io/knative-releases/knative.dev/eventing/cmd/controller
  digest: sha256:dd385d5632b8ce1a49c45421a3a11db91837c8fb12ea56c7ebde4f9aad2e825c
- name: gcr.io/knative-releases/knative.dev/eventing/cmd/webhook
  newName: gcr.io/knative-releases/knative.dev/eventing/cmd/webhook
  digest: sha256:3f6dfc52cfaf0b5a8e0c098f83f60eb237d3b8bfbbd4d0faea7c08fad98a1215
- name: gcr.io/knative-releases/knative.dev/eventing/cmd/mtping
  newName: gcr.io/knative-releases/knative.dev/eventing/cmd/mtping
  digest: sha256:2fc8713fb4807df0f5d8f9506d03c16c168eed61f19c04e04092266248bd0353
