apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "2lcJrms9FzlPdZITFLYjOwPaPUIHQbJxkR1neRnL0pCYiE98ZCUuhjKpWMPkhWcW\nntNpjOUkqjU6lqgciBL2my7L/rlqIXU1Sc606laVTZe6qRwpNPQR5zi5n4O5susE\nAmRlKl/4/jKLdU4VqsG56gvM9Gn4PuCkAx6FbUL0LSs="
